---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: exdns-1-k8s-gateway
    domain: "${SECRET_DOMAIN}"
    apex: exdns-1-k8s-gateway.networking
    ttl: 1
    service:
      type: LoadBalancer
      port: 20053
      useTcp: true
      loadBalancerIP: 10.10.0.1
      annotations:
        io.cilium/lb-ipam-ips: "10.10.0.1"
        tailscale.com/expose: "true"
        tailscale.com/hostname: "exdns-1-k8s-gateway"
      externalTrafficPolicy: Cluster
