---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=rancher/system-upgrade-controller
  - connector.yaml
  - secret.sops.yaml
  - helmrelease.yaml
