---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIMINIO_ROOT_PASSWORDO_SECRET_KEY }}"
  dataFrom:
  - extract:
      key: minio
