---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-03-21T23-13-43Z

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    env:
      TZ: Asia/Seoul
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      MINIO_PROMETHEUS_JOB_ID: minio
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_BROWSER_REDIRECT_URL: https://minio.chalk-ho.me
      MINIO_SERVER_URL: https://s3.chalk-ho.me
      MINIO_API_CORS_ALLOW_ORIGIN: https://minio.chalk-ho.me,https://s3.chalk-ho.me
    envFrom:
    - secretRef:
        name: minio-secret

    service:
      main:
        ports:
          http:
            port: &console-port 9001
          api:
            enabled: true
            port: &api-port 9000
    args:
    - server
    - /data
    - --console-address
    - :9001

    persistence:
      config:
        enabled: true
        storageClass: "openebs-hostpath"
        size: "300Gi"
        mountPath: /data

    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: internal
        hosts:
        - host: &host minio.chalk-ho.me
          paths:
          - path: /
            pathType: Prefix
            service:
              port: *console-port
        tls:
        - hosts:
          - *host
      s3:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: &s3host s3.chalk-ho.me
          paths:
          - path: /
            pathType: Prefix
            service:
              port: *api-port
        tls:
        - hosts:
          - *s3host

    serviceMonitor:
      main:
        enabled: true
        endpoints:
        - port: api
          scheme: http
          path: /minio/v2/metrics/cluster
          interval: 1m
          scrapeTimeout: 10s
