---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: volsync-system
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.2
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: home-assistant-secret
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.3.3@sha256:a4c2b7a75e8d5168a9e9f78d9d9f7f36435e2da07899e7faf5f6e3cdc4eebe56
            env:
              TZ: Asia/Seoul
              HASS_HTTP_TRUSTED_PROXY_1: 10.2.0.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.0.7.0/24
              HASS_HTTP_TRUSTED_PROXY_3: 10.12.0.0/16
              HASS_HTTP_TRUSTED_PROXY_4: 10.11.0.0/16
              HASS_HTTP_TRUSTED_PROXY_5: 10.10.0.0/16
              HASS_HTTP_TRUSTED_PROXY_7: 100.64.0.0/10
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.chalk-ho.ke
        hosts:
          - host: &host hass.chalk-ho.ke
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        storageClass: openebs-hostpath
        size: 20GiB
        accessMode: ReadWriteOnce
        globalMounts:
        - path: /config
      logs:
        type: emptyDir
        globalMounts:
        - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
        - path: /config/tts
      tmp:
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        memory: 2048M

    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.22.1
        workingDir: "/config"
        args:
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        - --auth
        - "none"
        env:
          TZ: Asia/Seoul
          HASS_SERVER: http://localhost:8123
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
        ingress:
          enabled: true
          ingressClassName: internal
          hosts:
          - host: hass-vscode.chalk-ho.me
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-vscode.chalk-ho.me
        volumeMounts:
        - name: config
          mountPath: /config
