---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backube.yaml
  - bitnami.yaml
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - descheduler.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - grafana.yaml
  - ingress-nginx.yaml
  - k8s-gateway.yaml
  - jetstack.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - onepassword-connect.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - rook-ceph.yaml
  - stakater.yaml
  - tailscale.yaml
