---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    fullnameOverride: onepassword-connect

    connect:
      # Denotes whether the 1Password Connect server will be deployed
      create: true

      # The number of replicas to run the 1Password Connect deployment
      replicas: 1

      # The name of 1Password Connect Application
      applicationName: onepassword-connect

      # The name of 1Password Connect Host
      host: onepassword-connect
      serviceType: LoadBalancer
      serviceAnnotations:
        io.cilium/lb-ipam-ips: "10.10.0.10"

      api:
        httpPort: 80
        httpsPort: 443

        serviceMonitor:
          enabled: true
