---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator
  namespace: flux-system
spec:
  targetNamespace: tailscale
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: cert-manager-issuers
  - name: external-secrets-stores
  path: ./kubernetes/apps/tailscale/operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale-operator-connectors
  namespace: flux-system
spec:
  targetNamespace: tailscale
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: tailscale-operator
  path: ./kubernetes/apps/tailscale/operator/connectors
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
