---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    template:
      engineVersion: v2
      data:
        client_id: "{{ .TAILSCALE_OPERATOR_CLIENT_ID }}"
        client_secret: "{{ .TAILSCALE_OPERATOR_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: tailscale
