apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    # annotations:
    # reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    # reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
stringData:
    client_id: ENC[AES256_GCM,data:91DC3tRh+SPrcJWb,iv:SRybM5W2c7XufhPv+ygrUsNciSPfpRXPpX4UJjat5Xc=,tag:VTyT5BEE8/pAmZOwoKBkBA==,type:str]
    client_secret: ENC[AES256_GCM,data:KLdOWzxMKKRq38uIA65ntm3cyoJHqFN99YrRplw4k6oCPYsXvTeT1lgAnqXratgjXaSBqIDUEcA4yNk=,iv:u7/Bf5+BAiRypt/65kyh5mq5kKfmY5QUO4l8l3advNg=,tag:dKCew1goy7OrRdaNeZT/pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10apg42ewu3y6sxpqes2auvnlfs37fvnkap5y8h6726xe6mhlda4sfpy0k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMWFUMFZBdTIvLzRYaTZn
            V3Q5dGRuOSt1QWoyampuSmlhQXB2dUs5UGxVCmw1eVFZT1FLejh4cGczbWtPMTZW
            blhJK0IrYjUrYjgyRW9PNWNxei9ISmcKLS0tIGpmQXRIMlM5UytXcnhhcm5TMFNV
            d1RRN3d1QlZOR3Qvck1RNCtwZDJKRGsKs8dsixA3prpqf6X8qru/jslB62jqmBUg
            mx24wQQBmgBcbm5FVXjklUf1PhwVuvEJ7+BcmgUAJTladDDTMVmnGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T00:31:30Z"
    mac: ENC[AES256_GCM,data:Nhl9HR6L0uDeVnI6dpao0B+BBlQwtaZ6Z4gpfqadAM8rI4ImW9VDQPutP8FqI+EsD5kRo7JIxgrOk/jyciE07+jP4Bk/QYpG/HuwUVkysalSTeKkyoAi44AI7InkzYGGLciEeWsNU+KHUHvxv0dJZg9LoLRrj+BI4NGVyuZDmF0=,iv:r/WzTJyd5eYnKucK2hhYeHvVx04iO1UiuYI60TIXOds=,tag:vcMp2V483/Nscn+3OJOC1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
