apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:1+2LRxbUuDoEXaxxUzNl0yDIxuSyu1XBjgeiHbHlZNDAFaRVb35g3dRLyx3JySVpFx58dP8qthEwv7eyN8U4janCC2/pA2vTglhuYfkB5FPoCkFkukImXsSfc7iUQw==,iv:EG+T+SD7XjXFYk04zmbykfnqtYET6JB8qJFYmHfuYdw=,tag:cP85qY1Hz6Vasi5Y7gmpTg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3JurQLQbuFlEtr4=,iv:mClbDDR46Pybfp19zJInWG/BPs++if1k1FYb/St2Zkg=,tag:6Z3SUt3sSxu0a6W5uyf7uQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yqPPUKB6KLdKQ8D7tHAyJqY=,iv:mPGmedHTypaPyDkDces3ZwUSqf2hk5P0M00gjeDBUu0=,tag:24B6R9ehl9fI95bWLLknsA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Znwh80lG7XdMGDC6lzs0LClddPrJT9iQCospx+k9emTJ7Rwz,iv:5TFiMhRkcWl9x2C9kgD5+HSLJKO+yLQ9KGJTz3wSlKI=,tag:5Hy5T/K0A4EiaB51Qyvtkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10apg42ewu3y6sxpqes2auvnlfs37fvnkap5y8h6726xe6mhlda4sfpy0k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbk51N3NXbGw4Z01GRHVZ
            eWk5ek9abUdMQ25kbDNsdXhST1NjUW4wVEZrCkVSbXl6MUg3ckVpVVhHZ0RZREdY
            U0NFN0Y4UVdzQjlBYlE5MWg5Y2pzQlEKLS0tIGdLcEZCSWIzdk5xVzgwaWhLTm1W
            N2xibjQ3K0c1UWpVdTNTVEQ5a2RiRDgKhyHyvNGM/StC+MDM87LyrUiuwHprJxvp
            uUTlJrbr/VxFu7TkwfLpFG+Stliegf13SThRYKEPLu6xjsuaK8dc2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T23:17:10Z"
    mac: ENC[AES256_GCM,data:maQGbLDDVEbx9nRz8TsiZa9rGXPCfobccCZGQQ9Mdli02y04vQAONY9XNzJUvspTsM0yIpMhQkpEIoSf4UebIDUi+ddp3Q+vExDc9QuEAkiIg+hcPa7aPZcmaOZ+ddmDdant86Pcs5auNSscE7DBd1TMsbL739Kdd+FWxNVK46A=,iv:gradtGGV3fQEoxHMLMpk63h3MduJOTJMYPkc4bGUYXg=,tag:+xdkwyWMbE+GA4zMFqXtqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
