---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Seoul"
  CLUSTER_CIDR: "10.11.0.0/16"
  POD_CIDR: "10.12.0.0/16"
  NODE_CIDR: "10.0.7.0/24"
  BGP_ADVERTISED_CIDR: "10.10.0.0/16"
