apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
type: Opaque
stringData:
    token: eyJhbGciOiJFUzI1NiIsImtpZCI6ImludTd4eG9rNmtxMjN3d2R2ZXc0dGw1bHB1IiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiRzc3M0xNUkpOUkJBWEcyWEczVFpRVkFBWUUiLCIxcGFzc3dvcmQuY29tL3Rva2VuIjoiR3VZbGEyc3dydXE5Y0NhV19qcDhqeHI1eXo0QjNUQVUiLCIxcGFzc3dvcmQuY29tL2Z0cyI6WyJ2YXVsdGFjY2VzcyJdLCIxcGFzc3dvcmQuY29tL3Z0cyI6W3sidSI6IjMzaDR2ZzRmdXc0c21xaXF0ZmR3dWdkbnFhIiwiYSI6NDk2fSx7InUiOiJtdHliY2E1cWp1ZDVsdGZkZGF6bjNkc2xzeSIsImEiOjQ5Nn1dLCJhdWQiOlsiY29tLjFwYXNzd29yZC5jb25uZWN0Il0sInN1YiI6IlozVEVSWUdYR1ZITlhEN1FIWk9QUklES05ZIiwiaWF0IjoxNzEwNzMwNzIyLCJpc3MiOiJjb20uMXBhc3N3b3JkLmI1IiwianRpIjoiY3d5dnhocXl2cnlydHZ4NmdteXBzZXVpemUifQ.IftyBT5ZXf8A1z4PV0Ts7Th6n4wVQI_MHt6vGaYHGBUXmkOA2V221BlR-5HUfoge8ZjpGhUJ-Kc0l2dnfKjDeg
