---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HASS_POSTGRES_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@pg16-rw.database.svc.cluster.local/home_assistant"
        LATITUDE: "{{ .LATITUDE }}"
        LONGITUDE: "{{ .LONGITUDE }}"
        # ALARMCD: "{{ .ALARMCD }}" /
        # SECURE_DEVICES_PIN: "{{ .SECURE_DEVICES_PIN }}"
        # OPNSENSE_USER: "{{ .OPNSENSE_USER }}"
        # OPNSENSE_KEY: "{{ .OPNSENSE_KEY }}"
        # DOORBELL_PASSWORD: "{{ .DOORBELL_PASSWORD }}"
        # Postgres Init

        INIT_POSTGRES_DBNAME: home_assistant
        INIT_POSTGRES_HOST: pg16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: home-assistant
  - extract:
      key: cloudnative-pg
