---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: openebs
    namespace: openebs-system
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      # Configure the main controller
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          # Configure the main application container
          main:
            image:
              # -- image repository
              repository: ghcr.io/onedr0p/home-assistant
              # -- image tag
              # this example is not automatically updated, so be sure to use the latest image
              tag: 2024.3.3

          # Configure the code-server sidecar
          code:
            dependsOn: main
            image:
              # -- image repository
              repository: ghcr.io/coder/code-server
              # -- image tag
              # this example is not automatically updated, so be sure to use the latest image
              tag: 4.22.0
            args:
            - --auth
            - "none"
            - --user-data-dir
            - "/config/.vscode"
            - --extensions-dir
            - "/config/.vscode"
            - --port
            - "8081"
            - "/config"

    service:
      # Configure a service for the main application
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8123
      # Configure a service for the code-server sidecar
      code:
        type: ClusterIP
        controller: main
        ports:
          http:
            port: 8081

    ingress:
      # Configure an Ingress for the main application
      main:
        className: "external"
        hosts:
        - host: &host "hass.chalk-ho.me"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
          - hosts:
              - *host
      # Configure an Ingress for the code-server sidecar
      code:
        className: "internal"
        hosts:
        - host: &host-code "hass-code.chalk-ho.me"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: code
              port: http
        tls:
        - hosts:
          - *host-code

    persistence:
      # Configure the main configuration storage location
      config:
        storageClass: openebs-hostpath
        size: 20Gi
        accessMode: ReadWriteOnce
        globalMounts:
        - path: /config
