apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kop5uL0Pv50HhNQssXdUk7E0iwW6Hv8w0D0t6I8fD4I=,iv:OF5XlFuHxug6hJmZRY7MmUvZk8J0Sv9tNMBDNfwBym8=,tag:Lkb0y1zA4S2FM5C494tz4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10apg42ewu3y6sxpqes2auvnlfs37fvnkap5y8h6726xe6mhlda4sfpy0k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYyswOWYrVnRxT2NKNEZx
            eTFqR2NIVDJCVkpaaTVXZFVmR0JjYlp2NWdVCjBTVmZGY1JLaVRLQVZFQ1EzM3Fq
            bk5COFJQSTlDejd6UjlDK24vdWRzZGcKLS0tIGxxRHRQanJyRENFYlZlRTQwOUN0
            L2JDOXkrUHJGYjZySC9RSjJTUDRKVUkKlkqNSGBgV3olv1qig39JxDXpyF/5wdVv
            LCN1FgU4Lt1wxmWMl9Jr4r7NKlf5ZJZ8beyGWcPOJZWZXw5Oiq1mvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T23:44:56Z"
    mac: ENC[AES256_GCM,data:u1GfUcUA6o0rpxx5M/ImqJkPDoD/7ANerANbYAxStP+iFJIt862gTf+PbTh7mUN7EFjzanl1Krj7uQE7AYMWkGk5WKBRYgSK+yNa6xJXYr3PI+1eDJolLTqb59sNdGgqatOA7PtNcrBQRDrXCCcGd4oas4NUSnRsmTEDUN7eLqM=,iv:HXa3fWm+FwgftwDxPO0VdxFeChVX6fzzWOAZowOKUe0=,tag:yg1ExhC9G6mpfyDvDh8ABw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
