apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:JO4xIo8QCqB7lLKe3iz7i/EAKyd92LGejyqQeSSQfUk=,iv:596x9lQOhKk+ZTFUxrOv6rJV60DaujUBbYzPFbS9fbY=,tag:ciIDX3/RpsclenhCrAuv0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10apg42ewu3y6sxpqes2auvnlfs37fvnkap5y8h6726xe6mhlda4sfpy0k7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cWxTQ3BlZWZSdFpRMlcw
            T0t5VTd4R2p2SHcxSWZCSTgxaUlKZzdiR2p3CktMd2FSemRNZ2RhYUtwb2ZYRENh
            eFlCNTV0S1J4bUVDTmNIdmhmL1lkUTQKLS0tIGdqZkwrQmIxR0NsWmNQVVJLSkY4
            YUo5YzZYNlY0ZVRRTDAyTTFtQXpoMFUKS8LVn4mQ5ZlfAUvyEFwmqS/IQF3Z/SRo
            tgC1bqcjf2RuDih29PyveoJmFyKiaHGWLonwJC7FF02Xf0ET8up9mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T23:17:10Z"
    mac: ENC[AES256_GCM,data:LO3TLfqdMT9Hk7PRZyhpMgK1CpYDI5ZL8myHIvYmKqlPM2oKZgCt+K6j++gLJ3xuFdlFqE6A3Wnp4CLD1/GaoAuBMW/miVawSRNkfFLtnFOOPkF97Fnl0YsQ69nK8OxL1lPWfwH7q8pyJYb3b5VHG4mabHdAVWDjLu8XGAa7mtk=,iv:F86U9CQ7S+SVv1zuElvK4wQ76hF7fE3NCHyTCb2xT30=,tag:n/TEySHYUn3tYshCom9d6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
